---
- hosts: "{{ variable_host | default('all') }}"
  gather_facts: yes
  become: yes
  tasks:
    - name: remove nginx-proxy old config
      file:
        path: '/opt/nginx-proxy.yml'
        state: absent
    # - name: create volumes directories
    #   file:
    #     path: /etc/{{ item[0] }}/{{ item[1] }}
    #     state: directory
    #   with_nested:
    #     - nginx-proxy-manager
    #     - [ 'data', 'letsencrypt', 'mysql' ]
    - name: copy new nginx-proxy config
      template:
        src: ./stack.yml.j2
        dest: /opt/nginx-proxy.yml
    - name: Deploy nginx proxy manager stack
      command: docker stack deploy -c /opt/nginx-proxy.yml nginx-proxy-manager
      run_once: true
