---
- hosts: master
  gather_facts: yes
  become: yes
  tasks:
    - name: create /ssl/nginx directory
      file:
        path: /ssl/nginx
        state: directory
    - name: create /ssl/data/certbot/conf directory
      file:
        path: /ssl/data/certbot/conf
        state: directory
    - name: create /ssl/data/certbot/www directory
      file:
        path: /ssl/data/certbot/www
        state: directory
    - name: remove old nginx config
      file:
        path: /ssl/nginx/app.conf
        state: absent
    - name: remove old docker-compose file
      file:
        path: /ssl/docker-compose.yml
        state: absent
    - name: remove old init-letsencrypt
      file:
        path: /ssl/init-letsencrypt.sh
        state: absent
    - name: copy new docker-compose file
      template:
        src: ./templates/app.conf.j2
        dest: /ssl/nginx/app.conf
    - name: copy new docker-compose file
      template:
        src: ./templates/docker-compose.yml.j2
        dest: /ssl/docker-compose.yml
    - name: copy new init-letsencrypt
      template:
        src: ./templates/init-letsencrypt.sh.j2
        dest: /ssl/init-letsencrypt.sh
        mode: u=rwx,g=r,o=r